name: Node.js CI

on:
  push:
    branches:
      - master  # or main, depending on your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
          ssh -o StrictHostKeyChecking=no root@88.222.244.11 'mkdir -p /path/to/deploy'
          rsync -avz --delete . root@88.222.244.11:/path/to/deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
